export default {
    local: {
        basePath: '/dist/',
        entryPointURL: 'http://127.0.0.1:8000',
        keyCloakBaseURL: 'https://auth-dev.tugraz.at/auth',
        keyCloakRealm: 'tugraz-vpu',
        keyCloakClientId: 'auth-dev-mw-frontend-local',
        matomoUrl: 'https://analytics.tugraz.at/',
        searchQRString: 'tugrazcheckin',
        matomoSiteId: 131,
    },
    development: {
        basePath: '/apps/checkin/',
        entryPointURL: 'https://api-dev.tugraz.at',
        keyCloakBaseURL: 'https://auth-dev.tugraz.at/auth',
        keyCloakRealm: 'tugraz-vpu',
        keyCloakClientId: 'dbp-check-in',
        matomoUrl: 'https://analytics.tugraz.at/',
        searchQRString: 'tugrazcheckin',
        matomoSiteId: 131,
    },
    demo: {
        basePath: '/apps/checkin/',
        entryPointURL: 'https://api-demo.tugraz.at',
        keyCloakBaseURL: 'https://auth-demo.tugraz.at/auth',
        keyCloakRealm: 'tugraz-vpu',
        keyCloakClientId: 'dbp-check-in',
        matomoUrl: 'https://analytics.tugraz.at/',
        searchQRString: 'tugrazcheckin',
        matomoSiteId: 131,
    },
    production: {
        basePath: '/',
        entryPointURL: 'https://api.tugraz.at',
        keyCloakBaseURL: 'https://auth.tugraz.at/auth',
        keyCloakRealm: 'tugraz',
        keyCloakClientId: 'checkin_tugraz_at-CHECKIN',
        matomoUrl: 'https://analytics.tugraz.at/',
        searchQRString: 'tugrazcheckin',
        matomoSiteId: 150,
    },
};